### ISSUE TITLE
Make confirmation before resetting clock

### ISSUE THREAD

**Issue by mddanishansari** [jacksonhvisuals/5217-web#32]
Title is self descriptive. If someone accidentally clicks the reset button(I did), it should ask for confirmation.

**Comment by jacksonhvisuals** [comment]
How is the title "self-destructive"? Did you mean "self-explanatory"?

Currently, the mobile app (https://5217.app) does not have a confirmation step for resetting the clock, and the web app is mainly mimicking the mobile app. I'll talk to Francisco about whether we should add this or not.

That said, if you look at normal clocks and timers, they don't have a confirmation step before resetting the clock. 

Thanks for the suggestion!

**Comment by jacksonhvisuals** [comment]
@franciscofranco thoughts?

**Comment by mddanishansari** [comment]
@jacksonhvisuals damn I meant "descriptive" . Lol.

**Comment by franciscofranco** [comment]
I'd rather have it show off a snackbar with a "Undo" for a couple seconds instead of asking for confirmation, but I have to give it a little thought.
