### ISSUE TITLE
Move dependencies to NPM & implement Webpack

### ISSUE THREAD

**Issue by myfrom** [jacksonhvisuals/5217-web#34]
The 5217 web app currently gets most third party resources from external servers. To improve loading times, decrease size and improve functionality of the service worker, they should be moved to self-hosted resources from NPM. This would also allow for new stuff such as minification, bundling and moving away from Materialize.css to new, modularised MDC.

Most of this was already discussed  in #33. I'm gonna take care of this and will have a PR ready before the end of next week. This issue is more to prevent someone else from starting duplicate work.

**Comment by myfrom** [comment]
Sorry but I'm gonna be a bit late with that. I think I'll get this by Tue. I'm very sorry for that, my plans got kinda broken and I still cannot find a reason behind this error that is thrown every time I try to build:
```
ERROR in   Error: /mnt/c/Users/myfro/Projects/5217-web/index.html:17188
      /* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(2), __webpack_require__(3)(module)))
```
@crutchcorn Do you have an idea what might be causing this?
<details><summary>My webpack.config.js</summary>
<p>

```javascript
const path = require('path'),
      HtmlWebpackPlugin = require('html-webpack-plugin'),
      CopyWebpackPlugin = require('copy-webpack-plugin'),
      CleanWebpackPlugin = require('clean-webpack-plugin'),
      { InjectManifest } = require('workbox-webpack-plugin');

module.exports = [{
  entry: './js/imports.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'js/imports.js',
  },
  module: {
    rules: [{{
      test: /\.js$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: '[path][name].js'
          }
        }, {
          loader: 'babel-loader',
          query: {
            presets: ['es2015']
          }
        }
      ],
      exclude: path.resolve(__dirname, 'js', 'imports.js')
    }, {
      test: /imports\.js$/,
      loader: 'babel-loader',
      query: {
        presets: ['es2015']
      }
    }, {
      test: /\.css$/,
      use: [
        { loader: 'style-loader' },
        { loader: 'css-loader' }
      ]
    }, {
      test: /\.scss$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: 'css/styles.css'
          }
        },
        { loader: 'extract-loader' },
        { loader: 'css-loader' },
        {
          loader: 'sass-loader',
          options: {
            includePaths: ['./node_modules']
          }
        }
      ]
    }, {
      test: /\.(jpe?g|gif|png|webp|ico|svg|woff|woff2|ttf|wav|mp3|json|eot)$/,
      use: [{
        loader: 'file-loader',
        options: {
          name: '[path][name].[ext]'
        }
      }]
    }]
  },
  plugins: [
    new CleanWebpackPlugin('dist'),
    new HtmlWebpackPlugin({
      template: 'index.html',
      minify: true
    }),
    new CopyWebpackPlugin([ './favicon/*', './sound/*' ]),
    new InjectManifest({
      swSrc: './service-worker.js',
      importWorkboxFrom: 'local'
    })
  ],
  devServer: {
    contentBase: path.join(__dirname, "dist")
  }
}];
```

</p>
</details>

**Comment by jacksonhvisuals** [comment]
Ya man, no rush at all. Take your time. (and I have never delved into the dark void that is Webpack so I have no idea heh)

 @myfrom

**Comment by myfrom** [comment]
I'm very, very sorry for the delay but I have been literary fighting with Webpack for the whole week. I finally got it to work yesterday and **I have all the working code ready**.

The only thing left is deploying it: as Webpack requires this additional step and builds to a separate directory I think it would be ideal to include a CI that would build and deploy the code for us. I've got very good experience with Travis from three of my other projects and if you would agree I could set up the config but you would need to enable it for this repo with your account.
*What do you think, @jacksonhvisuals?*
And also, if this would be the way to go, when should we deploy? On each master commit or on tags? I think the second option would be better.

**Comment by jacksonhvisuals** [comment]
@myfrom absolutely no problem about the delay. There is zero rush on this project. I’ve added you as a collaborator on the repo, are you able to set up Travis with that? 

I think deploying on tags would be ideal.

**Comment by myfrom** [comment]
I tried but sadly seems like only admin of the repo can enable it. But it's one time job, just set up once and it _(in theory :joy:)_ works forever.

If you haven't used Travis before, you need to sign up on [travis-ci.org](https://travis-ci.org), go to your profile and enable 5217-web. Next, you will need to go into [its settings](https://travis-ci.org/jacksonhvisuals/5217-web/settings) and add an environment variable, preferably named `GITHUB_TOKEN`, with your GitHub Access Token ([here's how to get it](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)) with `public-repo` scope. Don't forget to disable 'Show value in build log'.

I'll add the Travis config to my code and open a PR later today.

**Comment by jacksonhvisuals** [comment]
@myfrom gotcha. I’ll try to do this tonight when I get home from work. 👍🏼

**Comment by jacksonhvisuals** [comment]
Can you check if I set up Travis properly, @myfrom? Never done it before. It said that the build passed, but not sure if it worked.

**Comment by jacksonhvisuals** [comment]
Oops, there was something that made me think that it was able to get the token automatically, but that was a separate, general token (?) for my GH account. Anyway, added the `GITHUB_TOKEN` token and disabled the 'Show value in build log.'

Triggered another build, but nothing seems to have changed. Isn't Travis supposed to create a `public` folder for the compiled code? Maybe I'm not understanding it correctly. I've never done this before, so a bit of a noob here... @myfrom

**Comment by myfrom** [comment]
Everything's all right. It will kick in once you tag a release on this repo, then it will run the normal Webpack build and upload only the results onto a separate branch and deploy it to GH pages. `dist` won't appear on `master`.

**Comment by jacksonhvisuals** [comment]
Fantastic. I've created a new release, hopefully it all works and Travis does it's thing.

**Comment by jacksonhvisuals** [comment]
It worked! https://web.5217.app is now running the latest code!

That said, I noticed a few issues with the spacing that I've created a GH issue for. Feel free to fix them, but if not, I can do it. @myfrom
