### ISSUE TITLE
Security vulnerability with a dependency

### ISSUE THREAD

**Issue by jacksonhvisuals** [jacksonhvisuals/5217-web#36]
I think GH is acting up a bit, as it's not showing me what exactly is the problem, but I think it's in the hoek dependency. Can you look into this?

**Comment by myfrom** [comment]
I found it: a dependency that is responsible for compiling Sass files uses a dependency which uses another dependency which uses another two dependencies with security vulnerabilities. 🙃 

As far as I understand it, there's no way it could be used to compromise any security on our end.

The only thing to look out for would be including untrusted CSS files but I'm not sure if even that could really cause any problems.

As the new version of those tools are released, NPM will download the next time we run build and the issues should disappear.

Related: sass/node-sass#2355

**Comment by jacksonhvisuals** [comment]
Gotcha, thanks!
