### ISSUE TITLE
Modals freak out at certain widths

### ISSUE THREAD

**Issue by jacksonhvisuals** [jacksonhvisuals/5217-web#37]
They're too thin (slightly) at w960px, and it's (seriously) too thin down through w450px.

**Comment by jacksonhvisuals** [comment]
I'm looking at the About modal right now, and it feels like it could use some tweaking. From w1280px to w450px, I think it would be good to make some changes, making it a bit wider.

Obviously you've already done so much for the project, so you don't have to do this at all, I'm just adding this as an issue for future reference for myself if I ever feel like fixing it hehe

**Comment by myfrom** [comment]
It should be enough to tweak max-width a bit. I might do it in my free time if no-one does before I have some time.
Since you granted me the contributor privileges (which I’m very grateful for 😄) can I commit it straight to master when I fix this?

**Comment by jacksonhvisuals** [comment]
Feel free to commit to master!

**Comment by jacksonhvisuals** [comment]
Oh wait, you already did! Thanks so much, closing this issue.
