### ISSUE TITLE
Breakpoint positioning of overflow/reset buttons broken

### ISSUE THREAD

**Issue by jacksonhvisuals** [jacksonhvisuals/5217-web#38]
It looks fine down to about w530px, but as it no longer adjusts at the various breakpoints I had set up initially, anything below w530px looks bad, then at a certain point, unusable.

**Comment by myfrom** [comment]
Oh, yeah, sorry, I must have missed those small widths. I'm currently fixing this and other issues as well. PR coming in few minutes
