### ISSUE TITLE
Changes to Add to Homescreen in Chrome 68

### ISSUE THREAD

**Issue by myfrom** [jacksonhvisuals/5217-web#41]
Since [Chrome 68 (current stable version), A2HS (add to homescreen) dialog will behave differently](https://developers.google.com/web/updates/2018/06/a2hs-updates).

I'm not yet sure if those changes affect _related apps_ dialog but I think they do. I'm trying to reach out to Chrome Developers for clarification.

I think we should adapt the app to those changes as the new behaviour makes A2HS much less discoverable if we don't act on `beforeinstallprompt`.

I think the best way thing to implement this would be to listen for that event and then:
- Add 'Install' button to the three dot menu,
- show install button on the break screen
and one more idea that is rather optional:
- detect returning visits (eg. with a cookie 🍪) and in such case show install button before user starts the work cycle.

_What do you think?_

**Comment by jacksonhvisuals** [comment]
That sounds good. I’m currently without a real computer for the next
week/two weeks, so I’m unable to really investigate.

That said, what you’ve proposed sounds fantastic, thanks for all your hard
work. I wasn’t even aware of the new changes in 68 haha.

Side note: I can’t remember if we already explored this avenue, but how
difficult would it be to add the PWA to the Windows store?

**Comment by myfrom** [comment]
Thanks 😄

Sadly, I'm on a camp for the next week and a half so I won't be able to work on that too.

In the topic of Windows Store, I read a bit more about that and the only problem (theoretically) would be that someone would need to pay a sign-up fee and than it should be really simple, there's even a [web app](https://www.pwabuilder.com/) to build PWAs into Windows' app package.
There's also 'automatic indexing through Bing' which should search the web for PWAs and add them on Microsoft's behalf but I don't think it's public yet (damn, MS documentation is really fragmented). I can give you some [links](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/microsoft-store) if you have some much free time 😉

**Comment by jacksonhvisuals** [comment]
Gotcha. No rush at all, I guess these changes will be implemented sometime
in the future. That’s totally fine.

I’ll take a look at that Windows stuff.

**Comment by myfrom** [comment]
Started working on it. It would look like that:

<img src="https://user-images.githubusercontent.com/19410489/50728033-378d1b00-1124-11e9-9e30-311a5611a8bf.png" width="300" alt="5217-web-a2hs_ nexus 5x 1"/> <img src="https://user-images.githubusercontent.com/19410489/50728034-3825b180-1124-11e9-8afb-20b5d8f5ef75.png" width="300" alt="5217-web-a2hs_ nexus 5x 1"/>

And also, the button in the pause screen would show when a user returns to the app, before they start the first cycle.
What do you think, @jacksonhvisuals?
