### ISSUE TITLE
When 52 minutes complete timer sets back to 52 minutes.

### ISSUE THREAD

**Issue by TravelingLex** [jacksonhvisuals/5217-web#45]
Right now when my 52 minutes have completed, the timer starts a new 52 minute timer immediately.

**Comment by myfrom** [comment]
Thanks for the report, I'll look into it. Can I ask for a few more details:
- Is the second timer starting with a white background or blue background, like the first circle?
- What browser are you using?

**Comment by TravelingLex** [comment]
The second timer is with a blue background. I'm using Chrome.

**Comment by myfrom** [comment]
I've tried a few times and the timer works normally for me. I'll do some more advanced testing on the weekend

**Comment by TravelingLex** [comment]
I tried to replicate after that day and couldn't get it to fail. It works for me now. Thank you for your help.
