### ISSUE TITLE
options to edit 5217?

### ISSUE THREAD

**Issue by frafrichile** [jacksonhvisuals/5217-web#53]
Is it possible to edit the cycle?

**Comment by myfrom** [comment]
If you mean the amount of time - no, it isn't currently possible.

Custom timers are a paid feature in the original app so I'd be reluctant to add it here since then people could just use this version for free rather than the paid extension in the original one.

**Comment by frafrichile** [comment]
I would be down with paying the developer. There is another extension app called Vysor that allows you to pay through google.  etc Thanks!

**Comment by myfrom** [comment]
Sorry for the inconvenience and thanks for feedback but for now I don't think this feature will be added soon to this version of the app, however if you want you can use custom timers in the [original Android app](https://play.google.com/store/apps/details?id=com.franco.timer) with an in app purchase.

There are a few reasons for that, the biggest being that this one and the original apps are made by different developers but also handling payments, locking a feature behind a paywall in an open source app..

**Comment by frafrichile** [comment]
Makes sense Thank you!
